USE RAPPHIM
GO

CREATE TABLE LichSuTaiKhoan(
	MaTaiKhoanXoa VARCHAR(10) PRIMARY KEY, 
    TenDangNhap VARCHAR(50) UNIQUE NOT NULL, 
    Email VARCHAR(100) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    ThoiGianXoa DATETIME DEFAULT GETDATE()
);

CREATE OR ALTER TRIGGER trg_XOA_TAI_KHOAN
ON TAIKHOAN
INSTEAD OF DELETE
AS
BEGIN
    INSERT INTO LichSuTaiKhoan(MaTaiKhoanXoa, TenDangNhap, Email, MatKhau)
    SELECT MaTaiKhoan, TenDangNhap, Email, MatKhau
    FROM deleted

    DELETE TAIKHOAN
    WHERE MaTaiKhoan IN (SELECT MaTaiKhoan FROM deleted);
END
GO

BEGIN TRY 
DELETE TAIKHOAN WHERE MaTaiKhoan = '0000000004'
END TRY
BEGIN CATCH
    SELECT ERROR_MESSAGE() AS Loi;
END CATCH;

SELECT *
FROM LichSuTaiKhoan